# Site settings
title: Tejas Kulkarni's Blog
name: Tejas Kulkarni # your name
email: tejasdkulkarni@gmail.com # your email address
description: >
    Artificial Intelligence @ MIT
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://mrkulk.github.io" # the base hostname & protocol for your site
twitter_username: tejasdkulkarni # your Twitter username
github_username: mrkulk # your Github username
disqus_username: tejasdkulkarni # your disqus username

google-analytics:  # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
